name: Publish Python Package
# Upload to PyPI is triggered by creating & publishing a release in GitHub UI

on:
  release:
    # Run when a release is published or a prerelease is published (not on draft creation)
    types: [published, prereleased]

jobs:
  build:
    name: Build Python 🐍 distributions 📦 for publishing to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
      with:
        # Checkout the code including tags required for dynamic versioning
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version: "3.10"

    - name: Install Poetry
      run: |
        pipx install poetry
        pipx inject poetry poetry-dynamic-versioning

    - name: Set version for pre-release (PEP 440 compliant)
      if: github.event.release.prerelease == true
      shell: bash
      run: |
        BASE_VERSION="$(poetry version -s | sed 's/+.*//')"  # strip any local part
        DATE="$(date -u +%Y%m%d)"
        RUN="${{ github.run_number }}"
        SHA="$(git rev-parse --short HEAD)"
        PRERELEASE_VERSION="${BASE_VERSION}.dev${DATE}${RUN}+g${SHA}"
        echo "Setting version to ${PRERELEASE_VERSION}"
        poetry version "${PRERELEASE_VERSION}"

    - name: Build sdist & wheel
      run: poetry build

    - name: Store built distribution
      uses: actions/upload-artifact@v4.6.2
      with:
        name: distribution-files
        path: dist/

  pypi-publish:
    name: Build and publish Python 🐍 package 📦 to PyPI
    needs: build
    runs-on: ubuntu-latest
    # Uses trusted publishing. https://docs.pypi.org/trusted-publishers/adding-a-publisher/
    environment:
      name: pypi-release
      url: https://pypi.org/p/sssom-schema
    permissions:
      id-token: write  # required for OIDC trusted publishing
    steps:
      - name: Download built distribution
        uses: actions/download-artifact@v4.3.0
        with:
          name: distribution-files
          path: dist

      - name: Publish package 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          verbose: true
          skip-existing: true
